- webui.py
> Fix incorrect URL in password reset email

- templates/display.pt
> Update DOAP homepage URL

- templates/standard_template.pt
> Print copyright year dynamically

- README.rst
Even though it's legacy this make it a bit clearer how to run legacy PyPI. 
Personally I would nuke the section about running local database and filling it up, 
and only document the "through warehouse" way.
> Document how to run legacy PyPI in readme.

- templates/standard_template.pt
> Remove empty <a> tags

- config.py
- legacy_passwords.py
- requirements.txt
- store.py
> Upgrade password handling libraries

- webui.py
gracefully and quickly fail when redis is having a bad time.
> Wrap redis

- templates/confirm.pt
Waiting on pypa/warehouse#1573 before merge.
> Switch to the new ToS

- templates/standard_template.pt
- templates/tos.pt
- webui.py
> make Terms of Service accessible outside of signup flow

- webui.py
> Don't regen RSS on pointless endpoints

- webui.py
> We're not using distutils2, drop the logging

- store.py
> Remove unused store method

- webui.py
> Remove unused functions

- requirements.in
> Remove unused deps

- store.py
- webui.py
> Delete more stuff

- webui.py
> Kill the body of this method, not supported!

- config.py
- dogadapter.py
- fncache.py
- requirements.in
- requirements.txt
- rpc.py
- store.py
- webui.py
> datadogify pypi

- store.py
- webui.py
> Kill some more dead code as a result of removing the OpenID stuff

- README.rst
> Add code blocks to README where relevant

- store.py
- templates/files.pt
- templates/pkg_edit.pt
- templates/role_form.pt
- webui.py
half of this does not work, half of it should not work.
> Gut maintainer views
